### GET ALL MESSAGES
GET http://localhost:3000/messages

### GET A MESSAGE BASED ON ID
GET http://localhost:3000/messages/413

### SEND A MESSAGE
POST http://localhost:3000/messages
content-type: application/json

{
    "content":"vinay1"
}